### ISSUE TITLE
Source of SnippetPx.dll

### ISSUE THREAD

**Issue by ghostsquad** [KirkMunro/SnippetPx#1]
It's hard to contribute to this if the source code for SnippetPx.dll is not included in the repo. Can you add it?

**Comment by KirkMunro** [comment]
Sorry for the delay.  I've been away on holiday.  For all of my modules, all source code is on GitHub.  The model I follow is as follows:

master branch: contains the unsigned PowerShell module files
release branch: contains the signed PowerShell module files
assembly branch: contains the binary module source (if there is a binary module involved)

This model allows me to separate the PowerShell files needed to deploy a module from the C# code I use to write the nested binary module (if one is present).

For SnippetPx, just look in the assembly branch.  All of the binary source is there.

**Comment by ghostsquad** [comment]
Why not just write these cmdlets in PowerShell?

**Comment by KirkMunro** [comment]
Several reasons:
1. Because I can't. It is not possible to invoke a script block that is passed into a function in the scope in which that function was invoked. You can however invoke a script block that is passed into a compiled cmdlet in the scope in which that cmdlet was invoked. I identified that limitation quite a while ago, and got tired of waiting for them to make it possible to do that in PowerShell, so now I write binary cmdlets when it is more appropriate to do so. It is not possible to implement the equivalent of Invoke-Snippet in PowerShell.  PowerShell can do a lot, but it has plenty of limitations (other than this one), and binary modules allow me to do things I have wanted to do in PowerShell for years but simply was not able to do.
2. The DRY principle. The logic used to find snippets in the file system had to be implemented for Invoke-Snippet, and since it was already written, it was easier to write Get-Snippet in the binary module as well so that the logic could be shared between the cmdlets.
3. Performance. Compiled cmdlets beat interpreted PowerShell hands down, and I really wanted to make sure key features in this module and others were highly performant where they needed it most.

**Comment by ghostsquad** [comment]
Cool. Thanks for the clarification. This makes a lot of sense.

**Comment by ghostsquad** [comment]
This is actually a good idea for a cmdlet that I have, Invoke-Using, which
is to be like the 'using' statement in C# for IDisposable objects.
Currently, when invoking the scriptblock parameter passed in, value-type
variables outside of the scriptblock are available, but cannot be set,
which is normal behavior of PowerShell.

**Comment by KirkMunro** [comment]
Yeah, I have thought about implementing that functionality as well.  I started bringing "using" support to PowerShell, but only for namespaces so far in the Use-Namespace command in TypePx.  For the other part of using, you might be able to implement that with a snippet if you didn't want to go through the trouble of creating a compiled cmdlet.

Oh, and don't forget there is a Use verb.  I think that would be more appropriate (something like Use-IDisposable) than Invoke-Using.
